"""
Created trusted table.

Revision ID: 19ac78d5b70e
Revises: 55d7c78f3b9c
Create Date: 2023-09-06 22:05:40.715034

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "19ac78d5b70e"
down_revision = "55d7c78f3b9c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "trusted",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("uid", sa.BigInteger(), nullable=False),
        sa.Column("at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("trusted")
    # ### end Alembic commands ###
