"""
Created web map table.

Revision ID: 55d7c78f3b9c
Revises: 6ff05be1c24d
Create Date: 2023-09-02 23:42:28.858626

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "55d7c78f3b9c"
down_revision = "6ff05be1c24d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "web_map",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("sid", sa.BigInteger(), nullable=False),
        sa.Column("uid", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("matches", sa.Text(), nullable=False),
        sa.Column("xpath", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("web_map")
    # ### end Alembic commands ###
