"""
Link map, command metrics, drg builds.

Revision ID: 6ff05be1c24d
Revises:
Create Date: 2023-08-28 23:14:44.195939

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "6ff05be1c24d"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "command_metrics",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("command_name", sa.Text(), nullable=False),
        sa.Column("used_at", sa.DateTime(), nullable=True),
        sa.Column("successfully_completed", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "drg_builds",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("uid", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("dwarf_class", sa.Text(), nullable=False),
        sa.Column("build", sa.Text(), nullable=False),
        sa.Column("overclock", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "link_map",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("sid", sa.BigInteger(), nullable=False),
        sa.Column("uid", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("from_match", sa.Text(), nullable=False),
        sa.Column("to_match", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("link_map")
    op.drop_table("drg_builds")
    op.drop_table("command_metrics")
    # ### end Alembic commands ###
