"""
Added command metrics table.

Revision ID: 9006a86c02bb
Revises:
Create Date: 2023-07-23 15:13:39.062999
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9006a86c02bb"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "commandmetrics",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("command_name", sa.Text(), nullable=False),
        sa.Column("used_at", sa.DateTime(), nullable=False),
        sa.Column("successfully_completed", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("commandmetrics")
    # ### end Alembic commands ###
