"""
Changed table names.

Revision ID: f93e4669750d
Revises: 19ac78d5b70e
Create Date: 2023-09-16 21:44:40.958226

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "f93e4669750d"
down_revision = "19ac78d5b70e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "link_maps",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("server_id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("from_match", sa.Text(), nullable=False),
        sa.Column("to_match", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "web_maps",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("server_id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("matches", sa.Text(), nullable=False),
        sa.Column("xpath", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("web_map")
    op.drop_table("link_map")
    op.add_column("drg_builds", sa.Column("user_id", sa.BigInteger(), nullable=False))
    op.drop_column("drg_builds", "uid")
    op.add_column("trusted", sa.Column("user_id", sa.BigInteger(), nullable=False))
    op.create_unique_constraint(None, "trusted", ["user_id"])
    op.drop_column("trusted", "uid")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "trusted", sa.Column("uid", sa.BIGINT(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "trusted", type_="unique")
    op.drop_column("trusted", "user_id")
    op.add_column(
        "drg_builds", sa.Column("uid", sa.BIGINT(), autoincrement=False, nullable=False),
    )
    op.drop_column("drg_builds", "user_id")
    op.create_table(
        "link_map",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("sid", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("uid", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True,
        ),
        sa.Column("from_match", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("to_match", sa.TEXT(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name="link_map_pkey"),
    )
    op.create_table(
        "web_map",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("sid", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("uid", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True,
        ),
        sa.Column("matches", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("xpath", sa.TEXT(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name="web_map_pkey"),
    )
    op.drop_table("web_maps")
    op.drop_table("link_maps")
    # ### end Alembic commands ###
