version: 2

updates:
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "daily"
  groups:
    ci-dependencies:
      patterns:
      - "*"

- package-ecosystem: "pip"
  directory: "api"
  schedule:
    interval: "daily"
  groups:
    python-dependencies:
      patterns:
      - "*"

- package-ecosystem: "pip"
  directory: "bot"
  schedule:
    interval: "daily"
  groups:
    python-dependencies:
      patterns:
      - "*"

- package-ecosystem: "docker"
  directory: "/"
  schedule:
    interval: "daily"
  groups:
    docker-dependencies:
      patterns:
      - "*"
