version: "3.8"

x-logging-json: &logging_json
  logging:
    driver: "json-file"
    options:
      max-file: "5"
      max-size: "10m"

x-restart-policy:
  restart: unless-stopped

services:
  api:
    <<: *logging_json

    build:
      context: ./api
      dockerfile: Dockerfile

    env_file:
    - .env

    environment:
      XYTHRION_API_ENVIRONMENT: "dev"
      XYTHRION_API_DB_HOST: "postgres"
      XYTHRION_API_HOST: "0.0.0.0"

    volumes:
    - ./api:/api

    networks:
    - database-access
    - infra-metrics

  bot:
    <<: *logging_json

    build:
      context: ./bot
      dockerfile: Dockerfile

    environment:
      API_URL: "http://api:8001"

    env_file:
    - .env

    depends_on:
    - api

    volumes:
    - ./bot:/bot

    networks:
    - infra-metrics

networks:
  database-access:
    name: database-access
    external: true
  infra-metrics:
    name: infra-metrics
    external: true
