version: "3.8"

x-logging: &logging
  logging:
    driver: "json-file"
    options:
      max-file: "5"
      max-size: "10m"

x-restart-policy:
  restart: unless-stopped

services:
  api:
    <<: *logging

    build:
      context: ./api
      dockerfile: Dockerfile

    env_file:
    - .env

    volumes:
    - ./api:/api

    ports:
    - "8001:8001"

    networks:
    - database-access
    - xythrion

  bot:
    <<: *logging

    build:
      context: ./bot
      dockerfile: Dockerfile

    environment:
      API_URL: "http://api:8001"

    env_file:
    - .env

    depends_on:
    - api

    volumes:
    - ./bot:/bot

    networks:
    - xythrion

networks:
  database-access:
    name: database-access
    external: true
  xythrion:
    name: xythrion
    external: true
