version: "3.7"

x-logging: &logging
  logging:
    driver: "json-file"
    options:
      max-file: "5"
      max-size: "10m"

x-restart-policy: &restart_policy
  restart: unless-stopped

services:
  postgres:
    <<: *logging

    container_name: postgres

    image: postgres:15-alpine

    ports:
      - "5432:5432"

    environment:
      POSTGRES_DB: xythrion
      POSTGRES_PASSWORD: xythrion
      POSTGRES_USER: xythrion

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U xythrion"]
      interval: 2s
      timeout: 1s
      retries: 5

  metabase:
    <<: *logging

    container_name: metabase

    image: "metabase/metabase:latest"

    ports:
      - "3000:3000"

    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: xythrion
      MB_DB_USER: xythrion
      MB_DB_PASS: xythrion
      MB_DB_HOST: postgres
      MB_DB_PORT: 5432

    healthcheck:
      test: curl --fail -I http://localhost:3000/api/health || exit 1
      interval: 15s
      timeout: 5s
      retries: 5

  adminer:
    <<: *logging

    container_name: adminer

    image: adminer:latest

    ports:
      - "8080:8080"

  api:
    <<: *logging

    container_name: api

    build:
      context: ./api
      dockerfile: dev.Dockerfile

    env_file:
      - .env

    environment:
      POSTGRES_HOST: postgres

    volumes:
      - ./api:/api

    depends_on:
      - postgres

    ports:
      - "8000:8000"

  bot:
    <<: *logging

    container_name: bot

    build:
      context: ./xythrion
      dockerfile: dev.Dockerfile

    environment:
      API_URL: "http://api:8000"

    env_file:
      - .env

    depends_on:
      - api

    volumes:
      - ./bot:/bot
