version: "3.7"

x-logging: &logging
  logging:
    driver: "json-file"
    options:
      max-file: "5"
      max-size: "10m"

x-restart-policy: &restart_policy
  restart: unless-stopped

services:
  adminer:
    <<: *logging
    <<: *restart_policy

    image: adminer:latest

    ports:
      - 8080:8080

  postgres:
    <<: *logging
    <<: *restart_policy

    image: postgres:latest

    environment:
      POSTGRES_USER: xythrion
      POSTGRES_PASSWORD: xythrion
      POSTGRES_DB: xythrion

    ports:
      - "7777:5432"

    expose:
      - "7777:5432"

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U xythrion"]
      interval: 2s
      timeout: 1s
      retries: 5

    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
