version: "3.7"

x-logging: &logging
  logging:
    driver: "json-file"
    options:
      max-file: "5"
      max-size: "10m"

x-restart-policy:
  restart: unless-stopped

services:
  adminer:
    <<: *logging

    image: "docker.io/adminer:latest"

    ports:
    - "8080:8080"

  postgres:
    <<: *logging

    image: "docker.io/postgres:16-alpine"

    ports:
    - "5432:5432"

    environment:
      POSTGRES_DB: xythrion
      POSTGRES_PASSWORD: xythrion
      POSTGRES_USER: xythrion

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U xythrion"]
      interval: 2s
      timeout: 1s
      retries: 5

  watchtower:
    <<: *logging

    container_name: watchtower

    image: "docker.io/containrrr/watchtower"

    volumes:
    - /var/run/docker.sock:/var/run/docker.sock

    env_file:
    - .env

    environment:
      WATCHTOWER_NOTIFICATION_TEMPLATE: '{{range .}}{{.Time.Format "2006-01-02 15:04:05"}} ({{.Level}}): {{.Message}}{{println}}{{end}}'
      WATCHTOWER_LABEL_ENABLE: "true"
      WATCHTOWER_POLL_INTERVAL: 30

  api:
    <<: *logging

    image: "ghcr.io/xithrius/xythrion/api:latest"

    env_file:
    - .env

    environment:
      XYTHRION_API_RELOAD: "false"
      XYTHRION_API_DB_HOST: "postgres"
      XYTHRION_API_HOST: "0.0.0.0"

    volumes:
    - ./api:/api

    depends_on:
    - postgres

    ports:
    - "8001:8001"

    labels:
    - "com.centurylinklabs.watchtower.enable=true"

  bot:
    <<: *logging

    image: "ghcr.io/xithrius/xythrion/bot:latest"

    environment:
      API_URL: "http://api:8001"

    env_file:
    - .env

    depends_on:
    - api
    - postgres

    volumes:
    - ./bot:/bot

    labels:
    - "com.centurylinklabs.watchtower.enable=true"

  grafana:
    <<: *logging

    container_name: grafana

    image: "docker.io/grafana/grafana"

    volumes:
    - ./services/grafana/dashboards:/etc/grafana/provisioning/dashboards/

    ports:
    - "3030:3000"

  prometheus:
    <<: *logging

    container_name: prometheus

    image: "docker.io/prom/prometheus"

    volumes:
    - ./services/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

    ports:
    - "9090:9090"
