version: "3.7"

x-logging: &logging
  logging:
    driver: loki
    options:
      loki-url: 'http://localhost:3100/api/prom/push'
      loki-pipeline-stages: |
        - multiline:
            firstline: '^\d{4}-\d{2}-\d{2} \d{1,2}:\d{2}:\d{2}'
            max_wait_time: 3s
        - regex:
            expression: '^(?P<time>\d{4}-\d{2}-\d{2} \d{1,2}:\d{2}:\d{2},d{3}) (?P<message>(?s:.*))$$'

x-restart-policy:
  restart: unless-stopped

services:
  api:
    <<: *logging

    image: "ghcr.io/xithrius/xythrion/api:latest"

    env_file:
    - .env

    environment:
      XYTHRION_API_RELOAD: "false"
      XYTHRION_API_DB_HOST: "postgres"
      XYTHRION_API_HOST: "0.0.0.0"
      XYTHRION_API_OPENTELEMETRY_ENDPOINT: "http://tempo:4317"

    volumes:
    - ./api:/api

    ports:
    - "8001:8001"

    labels:
    - "com.centurylinklabs.watchtower.enable=true"

    networks:
    - database-access
    - api-metrics
    - xythrion

  bot:
    <<: *logging

    image: "ghcr.io/xithrius/xythrion/bot:latest"

    env_file:
    - .env

    environment:
      API_URL: "http://api:8001"

    depends_on:
    - api

    volumes:
    - ./bot:/bot

    labels:
    - "com.centurylinklabs.watchtower.enable=true"

    networks:
    - xythrion

networks:
  database-access:
    name: database-access
    external: true
  xythrion:
    name: xythrion
    external: true
  api-metrics:
    name: api-metrics
    external: true
