[tool.poetry]
name = "Xythrion"
version = "0.1.0"
description = "Discord graphing bot"
authors = ["Xithrius <xithrius@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "3.10.7"
disnake = "2.6.0"
python-dotenv = "0.21.0"
loguru = "0.6.0"
numpy = "1.23.3"
matplotlib = "3.6.0"

[tool.poetry.dev-dependencies]
flake8 = "4.0.1"
flake8-annotations = "2.9.0"
flake8-bugbear = "22.7.1"
flake8-docstrings = "1.6.0"
flake8-string-format = "0.3.0"
flake8-tidy-imports = "4.8.0"
flake8-todo = "0.7"
flake8-isort = "4.1.2.post0"
pep8-naming = "0.13.1"
pre-commit = "2.20.0"
taskipy = "1.10.2"
black = "22.8.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.taskipy.tasks]
start = "python -m xythrion"
lint = "pre-commit run --all-files"
precommit = "pre-commit install"

[tool.isort]
multi_line_output = 6
order_by_type = false
case_sensitive = true
combine_as_imports = true
line_length = 120
atomic = true
