[project]
dependencies = []
requires-python = ">=3.11"

[tool.pdm.dev-dependencies]
dev = [
    "-e file:///${PROJECT_ROOT}/xythrion",
    "-e file:///${PROJECT_ROOT}/api",
    "ruff>=0.1.3",
    "pre-commit>=3.3.3",
    "pytest>=7.4.0",
    "anyio>=3.7.1",
    "pytest-cov>=4.1.0",
    "pytest-env>=1.0.1",
    "pytest-xdist>=3.3.1",
]

[tool.pdm.scripts]
lint = "pre-commit run --all-files"
fmt = "ruff format ."
precommit = "pre-commit install"
test = "pytest"

[tool.pytest.ini_options]
filterwarnings = ["ignore::DeprecationWarning"]
