[project]
dependencies = []
requires-python = ">=3.11"

[tool.pdm.dev-dependencies]
dev = [
    "-e file:///${PROJECT_ROOT}/xythrion",
    "-e file:///${PROJECT_ROOT}/api",
    "ruff>=0.0.285",
    "pre-commit>=3.3.3",
    "black>=23.7.0",
]

[tool.pdm.scripts]
lint = "pre-commit run --all-files"
precommit = "pre-commit install"
test = "pytest"
