[project]
name = "xythrion-mono"
version = "0.1.0"
authors = [{ name = "Xithrius", email = "xithrius@gmail.com" }]
requires-python = ">=3.11"
license = { text = "MIT" }

[tool.rye]
virtual = true

[tool.rye.workspace]
members = ["api", "bot"]
