{
 "title": "FastAPI Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Memory usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"fastapi\"}",
     "legendFormat": "mem"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"fastapi\"}[30s])",
     "legendFormat": "cpu"
    }
   ]
  },
  {
   "title": "Total requests per minute",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(http_requests_total{job=\"fastapi\"}[1m])",
     "legendFormat": "{{ method }} {{ handler }}"
    }
   ]
  },
  {
   "title": "Average response time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_sum{job=\"fastapi\",handler!=\"none\"}[30s])",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Requests under 100ms",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "increase(http_request_duration_seconds_bucket{le=\"0.1\"}[1m]) \n/ ignoring (le) increase(http_request_duration_seconds_count[1m])",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Request duration [s] - p50",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "clocks" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, rate(http_request_duration_seconds_bucket{handler!=\"none\"}[30s]))",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Errors per second",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{status=\"5xx\"}[30s]))",
     "legendFormat": "errors"
    }
   ]
  },
  {
   "title": "Request duration [s] - p90",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "clocks" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, rate(http_request_duration_seconds_bucket{handler!=\"none\"}[30s]))",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "sum by (status) (rate(http_requests_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}