GITHUB_URL = "https://github.com/Xithrius/Xythrion"
BS4_HEADERS = {
    "User-Agent": "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) \
        AppleWebKit/537.36 (KHTML, like Gecko) \
        Chrome/58.0.3029.110 Safari/537.3",
    "Accept-Language": "en-US, en;q=0.5",
}

ERROR_REPLIES = (
    "Nuh uh",
    "Nah",
    "Something broke",
    "Oh good heavens",
    "Oh dear me",
    "Yeah, no",
    "This part is broken.",
    "No, I don't think I will.",
    "It says error, dummy",
    "Programmer diff",
    "Jarvis pull up the part where I care",
    "You egg",
    "I'm the monkey?!?",
    "Maybe the real error was the friends we made along the way.",
    "How am I doing so far?",
    "Father help",
    "We're gonna need to talk about this one.",
    "That one's going on the fridge",
    "Wait, what did you want me to do again?",
    "Wanna see me do it again?",
    "My opinion is didn't ask.",
    "Who put that wall there?",
    "Huh?",
    "Bruh moment",
    "It just be like that sometimes",
    "Me when I when the",
    "That's the way it do even tho it be.",
    "Augh my bones",
    "Your free trail to life has expired.",
    "I don't agree with you.",
    "Sorry I can't hear you let me take off my glasses.",
    "Skill issue",
    "Armor Piercing Fin Stabilized Discarding Sabot",
    "High Explosive Squash Head",
    "Oof.",
    "You lied to me, didn't you?",
    "I'm revoking your Dr. Pepper privileges.",
    "Do your are have big smartn't.",
    "I'm at soup!",
    "You're going to the shadow realm, Jimbo.",
    "F-15C ASMR",
    "Borgir.",
    "That's kinda cringe.",
    "You wouldn't download a car, would you?",
    "CAPTAIN! LOOK!",
    "You've been hit by, you've been struck by, truck.",
    "ALEXA 2019 FACEBOOK HACK NOW.",
    "I'm about to do what's called a pro gamer move.",
    "Smasnug.",
    "Do you mind?",
    "That was the mistake.",
    "One of us is bad at computers.",
    "Are you trying to kill me?",
    "I can't believe you've done this.",
    "Parry this, you filthy casual.",
    "L",
    "Unprecedented risk management strategies through scalable micro actions",
    "Damn you, Perry the Platypus",
    "Even in death, I still serve.",
    "Even in debt, I still serve.",
    "L + Ratio",
)
WARNING_REPLIES = (
    "Holup.",
    "The cake is a lie.",
    "Unlikely.",
    "There's like, nothing here.",
    "I swear I put it right there!",
    "Huh?",
    "Perhamps.",
    "Augh",
)
POSITIVE_REPLIES = (
    "It is done.",
    "Yep.",
    "Yuh.",
    "I think that worked.",
    "Indeedingly.",
    "Kerblam.",
)


class Colours:
    soft_green = 0x68C290
    soft_orange = 0xF9CB54
    soft_red = 0xCD6D6D
