"""
Created base tables.

Revision ID: e53d084bab02
Revises:
Create Date: 2023-10-28 20:25:20.885616

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "e53d084bab02"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "command_metrics",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("used_at", sa.DateTime(), nullable=False),
        sa.Column("command_name", sa.String(), nullable=False),
        sa.Column("successfully_completed", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "drg_builds",
        sa.Column("id", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("dwarf_class", sa.String(), nullable=False),
        sa.Column("build", sa.String(), nullable=False),
        sa.Column("overclock", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "link_maps",
        sa.Column("id", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("server_id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("from_match", sa.String(), nullable=False),
        sa.Column("to_match", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "pins",
        sa.Column("id", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("server_id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("message", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "trusted",
        sa.Column("id", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_table(
        "web_maps",
        sa.Column("id", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("server_id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("matches", sa.String(), nullable=False),
        sa.Column("xpath", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("web_maps")
    op.drop_table("trusted")
    op.drop_table("pins")
    op.drop_table("link_maps")
    op.drop_table("drg_builds")
    op.drop_table("command_metrics")
    # ### end Alembic commands ###
