"""
Removed DRG, more specific pin model.

Revision ID: 5bb6c7e09194
Revises: e53d084bab02
Create Date: 2023-12-23 21:12:19.638467

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "5bb6c7e09194"
down_revision = "e53d084bab02"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("drg_builds")
    op.add_column("pins", sa.Column("channel_id", sa.BigInteger(), nullable=False))
    op.add_column("pins", sa.Column("message_id", sa.BigInteger(), nullable=False))
    op.drop_column("pins", "message")
    op.drop_column("pins", "id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("pins", sa.Column("id", sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column("pins", sa.Column("message", sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column("pins", "message_id")
    op.drop_column("pins", "channel_id")
    op.create_table(
        "drg_builds",
        sa.Column("id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.Column("dwarf_class", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("build", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("overclock", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name="drg_builds_pkey"),
    )
    # ### end Alembic commands ###
