"""
Addition of channel map relationship in link map model.

Revision ID: 5f91f5cf93fe
Revises: 5bb6c7e09194
Create Date: 2024-01-06 21:20:57.914416

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "5f91f5cf93fe"
down_revision = "5bb6c7e09194"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "link_map_channels",
        sa.Column("server_id", sa.BigInteger(), nullable=False),
        sa.Column("input_channel_id", sa.BigInteger(), nullable=False),
        sa.Column("output_channel_id", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("server_id"),
    )
    op.add_column("link_maps", sa.Column("channel_map_server_id", sa.BigInteger(), nullable=False))
    op.add_column("link_maps", sa.Column("from_link", sa.String(), nullable=False))
    op.add_column("link_maps", sa.Column("to_link", sa.String(), nullable=False))
    op.create_foreign_key(None, "link_maps", "link_map_channels", ["channel_map_server_id"], ["server_id"])
    op.drop_column("link_maps", "from_match")
    op.drop_column("link_maps", "server_id")
    op.drop_column("link_maps", "user_id")
    op.drop_column("link_maps", "to_match")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("link_maps", sa.Column("to_match", sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column("link_maps", sa.Column("user_id", sa.BIGINT(), autoincrement=False, nullable=False))
    op.add_column("link_maps", sa.Column("server_id", sa.BIGINT(), autoincrement=False, nullable=False))
    op.add_column("link_maps", sa.Column("from_match", sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, "link_maps", type_="foreignkey")
    op.drop_column("link_maps", "to_link")
    op.drop_column("link_maps", "from_link")
    op.drop_column("link_maps", "channel_map_server_id")
    op.drop_table("link_map_channels")
    # ### end Alembic commands ###
