"""
Created base tables.

Revision ID: 5bff80c8a7f3
Revises:
Create Date: 2024-01-26 22:37:25.956239

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "5bff80c8a7f3"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "command_metrics",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("used_at", sa.DateTime(), nullable=False),
        sa.Column("command_name", sa.String(), nullable=False),
        sa.Column("successfully_completed", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "link_map_channels",
        sa.Column("server_id", sa.BigInteger(), nullable=False),
        sa.Column("input_channel_id", sa.BigInteger(), nullable=False),
        sa.Column("output_channel_id", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("server_id"),
    )
    op.create_table(
        "pins",
        sa.Column("server_id", sa.BigInteger(), nullable=False),
        sa.Column("channel_id", sa.BigInteger(), nullable=False),
        sa.Column("message_id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("server_id", "channel_id", "message_id"),
    )
    op.create_table(
        "trusted",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_table(
        "link_maps",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("from_link", sa.String(), nullable=False),
        sa.Column("to_link", sa.String(), nullable=True),
        sa.Column("xpath", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("channel_map_server_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["channel_map_server_id"],
            ["link_map_channels.server_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("link_maps")
    op.drop_table("trusted")
    op.drop_table("pins")
    op.drop_table("link_map_channels")
    op.drop_table("command_metrics")
    # ### end Alembic commands ###
