"""
to_link attribute on link maps is nullable.

Revision ID: 1875c6de1bdf
Revises: ffb8e9971cfc
Create Date: 2024-01-26 18:53:06.004384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1875c6de1bdf"
down_revision = "ffb8e9971cfc"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("link_maps", "to_link", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("link_maps", "to_link", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###
