name: Build

on:
  release:
    types:
    - published
  workflow_call:
    inputs:
      sha-tag:
        description: "A short-form SHA tag for the commit that triggered this workflow"
        required: true
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build

    runs-on: ubuntu-latest

    strategy:
      matrix:
        dir: ["api", "bot"]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: ./${{ matrix.dir }}
        file: ./${{ matrix.dir }}/Dockerfile
        push: ${{ github.ref == 'refs/heads/main' }}
        cache-from: type=registry,ref=ghcr.io/xithrius/xythrion-${{ matrix.dir }}:latest
        cache-to: type=inline
        tags: |
          ghcr.io/xithrius/xythrion-${{ matrix.dir }}:latest
          ghcr.io/xithrius/xythrion-${{ matrix.dir }}:${{ inputs.sha-tag }}
        build-args: |
          git_sha=${{ github.sha }}
